# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f5f619665fe83a3247061e95cf0ad957"
name = "QuickMF"
handle = "quickmf"
application_url = "https://roulette-theology-bicycle-workshop.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dyln-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://roulette-theology-bicycle-workshop.trycloudflare.com/auth/callback",
  "https://roulette-theology-bicycle-workshop.trycloudflare.com/auth/shopify/callback",
  "https://roulette-theology-bicycle-workshop.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
